import './globals.css'
import { Inter } from 'next/font/google'

import 'primeicons/primeicons.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PasTeal - A legjobb választás',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
